$RNFirebaseAsStaticFramework = true

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'barapaye' do
  config = use_native_modules!
  use_frameworks!
  use_react_native!(:path => config["reactNativePath"])

  pod 'RNLocalize', :path => '../node_modules/react-native-localize'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  pod 'react-native-contacts', :path => '../node_modules/react-native-contacts'

  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'

  # pod 'react-native-device-number', :path => '../node_modules/react-native-device-number'

  target 'barapayeTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end

target 'barapaye-tvOS' do
  # Pods for barapaye-tvOS

  target 'barapaye-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
